name: trufflehog scan
on:
  workflow_dispatch:
jobs:
  code_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --only-verified

